services:
  user-service:
    build:
      context: .
    container_name: user-service
    ports:
      - "8001:80"
  account-service:
    build:
      context: .
    container_name: account-service
    ports:
      - "8002:80"

