services:
  user-service:
    build:
      context: .
    container_name: user-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_EXCHANGE_NAME=user-service
    ports:
      - "8001:80"
  account-service:
    build:
      context: .
    container_name: account-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_EXCHANGE_NAME=account-service
    ports:
      - "8002:80"
  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
