[program:laravel-worker]
command=bash -c "php /app/artisan rabbitmq:queue-declare $RABBITMQ_QUEUE; php /app/artisan rabbitmq:queue-bind $RABBITMQ_QUEUE amq.direct --routing-key=$RABBITMQ_QUEUE; php /app/artisan rabbitmq:consume --queue=$RABBITMQ_QUEUE -vvv"
process_name=%(program_name)s
startsecs = 0
autostart = true
autorestart = true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
